USE goals_db;

INSERT INTO Users (firstName, lastName, userName, password, email)
VALUES ("katie", "wixted", "kwixted", "password", "kwixted@gmail.com"),
("Cheddar", "Kregg", "ckregg", "password", "cheddarkregg@gmail.com"),
("John", "Doe", "jdoe", "password", "jdoe@gmail.com"),
("Jane", "Doe", "janedoe", "password", "janedoe@gmail.com"),
("Joe", "Peters", "jpeters", "password", "jpeters@gmail.com"),
("Paul", "Komarek", "plomarek", "password", "pkomarek@gmail.com"),
("Karry", "Underwood", "kunderwood", "password", "kunderwood@gmail.com"),
("Liv", "Tyler", "ltyler", "password", "ltyler@gmail.com"),
("Peter", "Pecker", "ppecker", "password", "ppeker@gmail.com"),
("Steve", "Harvey", "sharvey", "password", "sharvey@gmail.com"),
("Larry", "Carry", "lcarry", "password", "lcarry@gmail.com"),
("Kim", "Jun", "kjun", "password", "kjun@gmail.com"),
("Trevor", "Guy", "tguy", "password", "tguy@gmail.com"),
("Pat", "Pat", "ppat", "password", "ppat@gmail.com"),
("Kyle", "Broflowski", "kbroflowski", "password", "kbroflowski@gmail.com"),
("Angie", "Wixted", "awixted", "password", "awixted@gmail.com"),
("Ava", "Adams", "aadams", "password", "aadams@gmail.com"),
("Chris", "Marrin", "cmarrin", "password", "cmarrin@gmail.com"),
("Abby", "Marrin", "amarrin", "password", "amarrin@gmail.com"),
("Cindy", "Komarek", "ckomarek", "password", "ckomarak@gmail.com"),
("Kevin", "Wixted", "kwixted", "password", "kwixted@gmail.com"),
("Jess", "Rodrigez", "jrodrigez", "password", "jrodriguez@gmail.com"),
("Clariza", "Moe", "cmoe", "password", "cmoe@gmail.com"),
("Eric", "Cartman", "ecartman", "password", "ecartman@gmail.com"),
("Craig", "Cheddar", "ccheddar", "password", "ccheddar@gmail.com"),
("Stan", "Marsh", "smarsh", "password", "smarsh@gmail.com"),
("Kenny", "McKormic", "kmckormic", "password", "kmckkormic@gmail.com");

INSERT INTO Goals (goal_name, goal_description, completed, UserId)
VALUES ("goal 1", "my first goal", 0, 2),
("goal 2", "my first goal", 1, 2),
("goal 3", "my first goal", 0, 3),
("goal 4", "my first goal", 0, 4),
("goal 5", "my first goal", 0, 5),
("goal 6", "my first goal", 0, 5),
("goal 7", "my first goal", 0, 2),
("goal 8", "my first goal", 0, 6),
("goal 9", "my first goal", 0, 6),
("goal 10", "my first goal", 0, 7),
("goal 12", "my first goal", 0, 7),
("goal 13", "my first goal", 0, 8),
("goal 14", "my first goal", 0, 8),
("goal 15", "my first goal", 0, 9),
("goal 16", "my first goal", 0, 10),
("goal 17", "my first goal", 0, 2),
("goal 18", "my first goal", 0, 12),
("goal 19", "my first goal", 0, 22),
("goal 20", "my first goal", 0, 22),
("goal 21", "my first goal", 0, 21),
("goal 23", "my first goal", 0, 23),
("goal 24", "my first goal", 0, 24),
("goal 25", "my first goal", 0, 25),
("goal 26", "my first goal", 0, 26),
("goal 27", "my first goal", 0, 27),
("goal 28", "my first goal", 0, 2),
("goal 29", "my first goal", 0, 2),
("goal 30", "my first goal", 0, 2);
