USE goals_db;

INSERT INTO Users (firstName, lastName, userName, password, email)
VALUES ("katie", "wixted", "kwixted", "password", "kwixted@gmail.com"),
("Cheddar", "Kregg", "ckregg", "password", "cheddarkregg@gmail.com"),
("John", "Doe", "jdoe", "password", "jdoe@gmail.com"),
("Jane", "Doe", "janedoe", "password", "janedoe@gmail.com"),
("Joe", "Peters", "jpeters", "password", "jpeters@gmail.com"),
("Paul", "Komarek", "plomarek", "password", "pkomarek@gmail.com"),
("Karry", "Underwood", "kunderwood", "password", "kunderwood@gmail.com"),
("Liv", "Tyler", "ltyler", "password", "ltyler@gmail.com"),
("Peter", "Pecker", "ppecker", "password", "ppeker@gmail.com"),
("Steve", "Harvey", "sharvey", "password", "sharvey@gmail.com"),
("Larry", "Carry", "lcarry", "password", "lcarry@gmail.com"),
("Kim", "Jun", "kjun", "password", "kjun@gmail.com"),
("Trevor", "Guy", "tguy", "password", "tguy@gmail.com"),
("Pat", "Pat", "ppat", "password", "ppat@gmail.com"),
("Kyle", "Broflowski", "kbroflowski", "password", "kbroflowski@gmail.com"),
("Angie", "Wixted", "awixted", "password", "awixted@gmail.com"),
("Ava", "Adams", "aadams", "password", "aadams@gmail.com"),
("Chris", "Marrin", "cmarrin", "password", "cmarrin@gmail.com"),
("Abby", "Marrin", "amarrin", "password", "amarrin@gmail.com"),
("Cindy", "Komarek", "ckomarek", "password", "ckomarak@gmail.com"),
("Kevin", "Wixted", "kwixted", "password", "kwixted@gmail.com"),
("Jess", "Rodrigez", "jrodrigez", "password", "jrodriguez@gmail.com"),
("Clariza", "Moe", "cmoe", "password", "cmoe@gmail.com"),
("Eric", "Cartman", "ecartman", "password", "ecartman@gmail.com"),
("Craig", "Cheddar", "ccheddar", "password", "ccheddar@gmail.com"),
("Stan", "Marsh", "smarsh", "password", "smarsh@gmail.com"),
("Kenny", "McKormic", "kmckormic", "password", "kmckkormic@gmail.com");